[build]
  base = "/"
  publish = ".next"  # This should be the directory where Next.js stores the production build
  functions = "netlify/functions"  # Path to your function files
  command = "npm run build"  # Run Next.js build command

[functions]
  # Optional: Configure custom settings for functions
  directory = "netlify/functions"  # This is where your function files are stored
  node_bundler = "esbuild"         # Use esbuild for bundling (optional)
  
  [functions.memory]
  memory = 1024                   # Set memory for functions (optional)

  timeout = 10                    # Set timeout in seconds (optional)

[[plugins]]
  package = "@netlify/plugin-nextjs"